export const TOOL_CHINESE_TEXT: Readonly<Record<string, string>> = {
  "Xprite Tools": "Xprite 工具",
  "Xprite Editor": "Xprite 编辑器",
  "Xprite Aseprite Viewer": "Xprite Aseprite 查看器",
  "Xprite GIF to Sprite Sheet": "Xprite GIF 转精灵表",
  "Xprite Animal Crossing Design Converter": "Xprite 动物森友会设计转换器",
  "Aseprite Viewer": "Aseprite 查看器",
  "GIF to Sprite Sheet": "GIF 转精灵表",
  "Animal Crossing Design Converter": "动物森友会设计转换器",
  "Processed on your device. No cloud upload.": "文件在本地处理，不上传云端。",
  "Files stay on your device. No cloud upload.": "文件只在本地处理，不上传云端。",
  "Pixel Art Tools | Xprite": "像素画工具 | Xprite",
  "Pixel art tools": "像素画工具",
  "Create pixel art, preview Aseprite projects and convert GIF animations into sprite sheets. Files are processed on your device without uploading them to the cloud.":
    "创作像素画、预览 Aseprite 工程，将 GIF 动画转换为精灵表。文件在本地处理，不上传云端。",
  "Inspect an Aseprite file": "查看 Aseprite 文件",
  "Aseprite Viewer | Xprite": "Aseprite 查看器 | Xprite",
  "Preview Aseprite projects and export PNG frames or GIF animations.":
    "预览 Aseprite 工程，导出 PNG 单帧或 GIF 动画。",
  "Open Aseprite projects, preview layers and animation, and export PNG frames or GIF animations in your browser. Files stay on your device, with no cloud upload.":
    "在浏览器中打开 Aseprite 工程、查看图层和动画，导出 PNG 单帧或 GIF 动画。文件只在本地处理，不上传云端。",
  "Choose an Aseprite file": "选择 Aseprite 文件",
  "Open file": "打开文件",
  "Open file…": "打开文件…",
  "Drop an .ase or .aseprite file": "拖入 .ase 或 .aseprite 文件",
  "Turn a GIF into a sprite sheet": "将 GIF 转换为精灵表",
  "GIF to Sprite Sheet | Xprite": "GIF 转精灵表 | Xprite",
  "Convert GIF animations into PNG sprite sheets with JSON frame data.":
    "将 GIF 动画转换为 PNG 精灵表，并导出 JSON 帧数据。",
  "Turn GIF animations into PNG sprite sheets with custom layouts and spacing. Download frame coordinates and timing as JSON. Files stay on your device, with no cloud upload.":
    "将 GIF 动画排成 PNG 精灵表，设置排列方式和间距，下载包含帧坐标和时长的 JSON。文件只在本地处理，不上传云端。",
  "Choose a GIF file": "选择 GIF 文件",
  "Open GIF": "打开 GIF",
  "Open GIF…": "打开 GIF…",
  "Drop a GIF file": "拖入 GIF 文件",
  "Make a design for your island": "制作岛屿设计",
  "Animal Crossing Design Converter: PNG & Aseprite | Xprite":
    "动物森友会设计转换器：PNG 与 Aseprite | Xprite",
  "Convert PNG images and Aseprite tilemaps into island designs, or open an existing design QR code and export it unchanged.":
    "将 PNG 图片和 Aseprite 瓦片地图转换为岛屿设计，或打开已有设计二维码并原样导出。",
  "Create Animal Crossing island design QR codes from PNG images and Aseprite tilemaps, or read normal design QR images and export their original data. Files stay on your device.":
    "用 PNG 图片和 Aseprite 瓦片地图生成动物森友会设计二维码，或读取普通设计二维码并导出原始数据。文件只在本地处理。",
  "Choose artwork or an Animal Crossing QR image": "选择作品或动物森友会二维码图片",
  "Drop artwork, a QR image or an .acnl file": "拖入作品、二维码图片或 .acnl 文件",
  "Free online pixel art editor": "免费在线像素画编辑器",
  "Draw pixel art and animate sprites with layers, frames and palettes.":
    "使用图层、帧和调色板创作像素画与精灵动画。",
  "Open and save .aseprite projects.": "打开和保存 .aseprite 工程。",
  "Create pixel art and animations in Xprite. Open and save Aseprite projects in your browser.":
    "在 Xprite 中创作像素画与动画，在浏览器中打开和保存 Aseprite 工程。",
  Applications: "应用程序",
  Tools: "工具",
  "All tools": "全部工具",
  "Tool navigation": "工具导航",
  "Tools directory": "工具目录",
  "Desktop shortcuts": "桌面快捷入口",
  "Page scroll": "页面滚动",
  "Read Me": "使用说明",
  "Hide {name}": "隐藏 {name}",
  "Close note": "关闭便签",
  "Collapse note": "折叠便签",
  "Expand note": "展开便签",
  "Resize note": "调整便签大小",
  note: "便签",
  "User guide": "使用指南",
  "Open an application from the Applications folder.": "从应用程序文件夹打开一个工具。",
  "Draw and animate pixel art.": "绘画像素画并制作动画。",
  "Inspect layers and animation.": "查看图层和动画。",
  "Arrange animation frames.": "排列动画帧。",
  "Create island design QR codes.": "制作岛屿设计二维码。",
  File: "文件",
  "Open example": "打开示例",
  "Try example": "试用示例",
  "Drop to open": "松开即可打开",
  "Hello sprite animation preview": "Hello 精灵动画预览",
  "Hello GIF animation preview": "Hello GIF 动画预览",
  "ACNH Winding Cobblestone Path by Amy, with transparent edges":
    "Amy 制作的动物森友会曲折鹅卵石道路，边缘透明",
  "ACNH Winding Cobblestone Path by": "动物森友会曲折鹅卵石道路，作者：",
  "Edit in Xprite": "在 Xprite 中编辑",
  "Export animation (.gif)": "导出动画（.gif）",
  "Export current frame (.png)": "导出当前帧（.png）",
  "Current frame (.png)": "当前帧（.png）",
  "Export sprite sheet (.png)": "导出精灵表（.png）",
  "Export frame data (.json)": "导出帧数据（.json）",
  "Export GIF": "导出 GIF",
  "Export PNG": "导出 PNG",
  Export: "导出",
  "Exporting…": "正在导出…",
  Animation: "动画",
  Timeline: "时间轴",
  Layers: "图层",
  Frame: "帧",
  "Animation range": "动画范围",
  "All frames": "所有帧",
  "Playback controls": "播放控件",
  "First frame": "第一帧",
  "First frame (Home)": "第一帧（Home）",
  "Previous frame": "上一帧",
  "Previous frame (Left)": "上一帧（左方向键）",
  "Next frame": "下一帧",
  "Next frame (Right)": "下一帧（右方向键）",
  "Last frame": "最后一帧",
  "Last frame (End)": "最后一帧（End）",
  "Play animation": "播放动画",
  "Play animation (Space)": "播放动画（空格）",
  "Pause animation": "暂停动画",
  "Pause animation (Space)": "暂停动画（空格）",
  "Current frame and its duration": "当前帧与时长",
  "Source frame": "源帧",
  "Zoom:": "缩放：",
  "Preview zoom": "预览缩放",
  Fit: "适合窗口",
  Preview: "预览",
  "Sprite preview. Space to play or pause, arrow keys to change frame.":
    "精灵预览。空格播放或暂停，方向键切换帧。",
  "Sprite sheet preview. Drag to pan, scroll to zoom, double-click to fit.":
    "精灵表预览。拖动平移，滚动缩放，双击适合窗口。",
  "Pattern preview. Drag to pan, scroll to zoom, double-click to fit.":
    "图案预览。拖动平移，滚动缩放，双击适合窗口。",
  "Sheet layout": "精灵表布局",
  "Sheet settings": "精灵表设置",
  "Sheet type": "精灵表类型",
  "Layout:": "排列方式：",
  "By rows": "按行排列",
  "By columns": "按列排列",
  Horizontal: "水平",
  Vertical: "垂直",
  Rows: "行数",
  Columns: "列数",
  "Border padding": "边缘留白",
  "Frame spacing": "帧间距",
  "Power of two": "尺寸为 2 的幂",
  "Round sheet dimensions up without scaling frames": "向上补齐精灵表尺寸，不缩放帧",
  "Imported design": "已导入设计",
  "Sprite sheet": "精灵表",
  Original: "原图",
  Converted: "转换结果",
  "Tile grid": "图块网格",
  "Each design is 32 × 32 pixels with up to 15 colors and transparency.":
    "每个设计为 32 × 32 像素，最多使用 15 种颜色并支持透明区域。",
  "Design information": "设计信息",
  Title: "标题",
  Creator: "作者",
  "Creator and island": "作者与岛屿",
  "Island / town": "岛屿／城镇",
  "Ready to export. The original design is preserved.": "可以导出了。原设计保持不变。",
  "Image layout": "图片布局",
  "Convert as": "转换方式",
  "One design": "单个设计",
  "Split into tiles": "拆分为图块",
  "Cell width": "图块宽度",
  "Cell height": "图块高度",
  "Start X": "起点 X",
  "Start Y": "起点 Y",
  "Spacing X": "水平间距",
  "Spacing Y": "垂直间距",
  "Offsets and spacing": "偏移与间距",
  "Generate QR codes": "生成二维码",
  "Download QR PNG": "下载二维码 PNG",
  "Design QR code": "设计二维码",
  "Selected tile": "所选图块",
  "Design to scan": "要扫描的设计",
  "Design tiles": "设计图块",
  "Animal Crossing design QR code": "动物森友会设计二维码",
  "How to import": "如何导入",
  "In Nintendo Switch App, open NookLink → Designs and scan this QR code. Download it in the game before scanning the next tile. Nintendo Switch Online membership is required.":
    "在 Nintendo Switch App 中打开 NookLink → 我的设计，扫描二维码。在扫描下一块之前，先在游戏中下载当前设计。需要 Nintendo Switch Online 会员。",
  "Generate designs to preview and download their QR codes.": "生成设计后即可预览和下载二维码。",
  "Island preview": "岛屿预览",
  "Preview status": "预览状态",
  Settings: "设置",
  Ground: "地面",
  "Ground preset": "地面预设",
  "Spring grass": "春季草地",
  "Summer grass": "夏季草地",
  "Autumn grass": "秋季草地",
  Tilt: "倾斜视角",
  Top: "俯视",
  Close: "近景",
  Colors: "颜色",
  "Ground design colors": "地面设计颜色",
  "QR palette": "二维码调色板",
  Placement: "摆放方式",
  "Ground placement": "地面摆放",
  "Nearby 3 × 3": "周围 3 × 3",
  "Repeat selected": "重复所选设计",
  Repeat: "重复次数",
  "Pattern repeat count": "图案重复次数",
  "Ground texture filtering": "地面纹理过滤",
  Smooth: "平滑",
  "Pixel sharp": "清晰像素",
  "Ground grid": "地面网格",
  "Interactive island ground preview": "可交互的岛屿地面预览",
  "Drag to tilt; scroll or pinch to zoom. Transparent pixels reveal the grass.":
    "拖动调整视角，滚动或捏合缩放。透明像素会露出草地。",
  "The 3D preview is unavailable in this browser.": "此浏览器无法显示 3D 预览。",
  "Opening…": "正在打开…",
  "Ready to export the original design.": "可以导出原设计了。",
  "QR export uses the New Leaf import palette. Check Converted for the exported colors.":
    "二维码导出使用《来吧！动物森友会》的导入调色板，可在转换结果中查看导出颜色。",
  "Set the image layout, then generate designs. The grid shows the source area of each tile.":
    "设置图片布局后生成设计，网格表示每个图块的源图范围。",
  "Loading…": "正在加载…",
  "Loading preview…": "正在加载预览…",
  "Generating…": "正在生成…",
  "Downloading…": "正在下载…",
  "Choose a GIF file.": "请选择 GIF 文件。",
  "Choose an .ase or .aseprite file.": "请选择 .ase 或 .aseprite 文件。",
  "This file could not be opened.": "无法打开此文件。",
  "The example could not be loaded. Choose a file to continue.": "无法加载示例，请选择文件继续。",
  "The example could not be loaded.": "无法加载示例。",
  "This GIF could not be opened.": "无法打开此 GIF。",
  "This layout could not be generated.": "无法生成此布局。",
  "The download failed. Try again.": "下载失败，请重试。",
  "The export failed. Try again.": "导出失败，请重试。",
  "The file could not be exported. Please try again.": "无法导出文件，请重试。",
  "The editor could not be opened. Please try again.": "无法打开编辑器，请重试。",
  "The file could not be sent to the editor.": "无法将文件发送到编辑器。",
  "This animation is too large to export as GIF. Choose a shorter animation tag or export the current frame as PNG.":
    "此动画过大，无法导出 GIF。请选择更短的动画标签，或将当前帧导出为 PNG。",
  "Choose a file no larger than 64 MiB.": "请选择不超过 64 MiB 的文件。",
  "Choose a GIF no larger than 64 MiB.": "请选择不超过 64 MiB 的 GIF。",
  "Choose an Aseprite file no larger than 64 MiB.": "请选择不超过 64 MiB 的 Aseprite 文件。",
  "Choose PNG, JPEG, .acnl or Aseprite. Single normal-design QR images are supported.":
    "请选择 PNG、JPEG、.acnl 或 Aseprite 文件。支持单张普通设计二维码图片。",
  "Choose a PNG with at most 16 million pixels.": "请选择不超过 1600 万像素的 PNG。",
  "The output could not be generated.": "无法生成输出文件。",
};
