import { createContext, useContext } from "react";

import type { ClipboardCapabilities } from "$/managers/clipboard";
import type { DockEdge } from "$/managers/workspace/dock-edge";
import type {
  WorkspaceDockNode,
  WorkspacePaneSnapshot,
} from "$/managers/workspace/document-workspace";
import type { RecoveryItem } from "$/managers/workspace/recovery-presentation";
export interface EditorActions {
  backupActive?: boolean;
  recoveryProblem?: string;
  retryRecovery?: () => void;
  recoveryOpen?: boolean;
  recoveryTabOpen?: boolean;
  recoverySelectedIds?: readonly string[];
  selectRecoveryProjects?: (ids: readonly string[]) => void;
  selectRecovery?: () => void;
  closeRecovery?: () => void;
  recoverFiles?: () => void;
  leaveRecovery?: () => void;
  recoveryItems?: readonly RecoveryItem[];
  recoveryBusy?: boolean;
  recoveryLoading?: boolean;
  recoverProjects?: (ids: readonly string[]) => void;
  deleteRecoveryProjects?: (ids: readonly string[]) => void;
  refreshRecovery?: () => void;
  clipboardCapabilities: ClipboardCapabilities;
  canSave: boolean;
  canStartInteraction: boolean;
  new: () => void;
  preferences: () => void;
  open: () => void;
  closeDocument: () => void;
  closeAllDocuments: () => void;
  copy: () => void;
  copyMerged: () => void;
  cut: () => void;
  paste: () => void;
  pasteNewLayer: () => void;
  pasteNewReferenceLayer: () => void;
  pasteNewSprite: () => void;
  newSpriteFromSelection: () => void;
  duplicateSprite: () => void;
  keyboardShortcuts: () => void;
  userGuide: () => void;
  about: () => void;
  feedback: () => void;
  donate: () => void;
  exit: () => void;
  loadRecentFiles?: () => void;
  canClearRecentFiles: boolean;
  clearRecentFiles: () => void;
  canReopenClosedFile: boolean;
  reopenClosedFile: () => void;
  prepareText?: () => void;
  recentFiles: readonly {
    id: string;
    name: string;
    width: number;
    height: number;
    pinned?: boolean;
    isOpen?: boolean;
  }[];
  openRecent: (id: string) => void;
  pinRecent: (id: string, pinned: boolean) => void;
  downloadRecent?: (id: string) => void;
  downloadRecentBusy?: boolean;
  deleteBrowserCopy?: (id: string) => void;
  deleteBrowserCopyBusy?: boolean;
  documentTabs: readonly {
    id: string;
    name: string;
    modified: boolean;
  }[];
  activeDocumentId: string;
  canSelectOtherDocumentTab: boolean;
  nextDocumentTab: () => void;
  previousDocumentTab: () => void;
  selectDocumentTab: (id: string) => void;
  reorderDocumentTab: (id: string, targetId: string, paneId?: string) => void;
  closeDocumentTab: (id: string) => void;
  duplicateDocumentView?: (id: string) => void;
  workspacePanes: readonly WorkspacePaneSnapshot[];
  workspaceDockTree: WorkspaceDockNode;
  workspaceRootPaneId: string;
  selectPaneTab: (paneId: string, id: string) => void;
  activateWorkspacePane: (paneId: string) => void;
  moveDocumentTab: (id: string, paneId: string, targetId?: string, before?: boolean) => void;
  splitDocumentTab: (id: string, paneId: string, edge: DockEdge) => void;
  resizeWorkspaceSplit: (splitId: string, ratio: number) => void;
  save: () => void;
  saveAs: () => void;
  exportFile: () => void;
  exportCopy: () => void;
  share?: () => void;
  exportAnimalCrossing?: () => void;
  exportSpriteSheet?: () => void;
  exportTileset?: () => void;
  importSpriteSheet?: () => void;
  repeatLastExport?: () => void;
  canRepeatExport?: boolean;
  color: (target: "foreground" | "background") => void;
  text: () => void;
}
export const EditorActionsContext = createContext<EditorActions | null>(null);
export const useEditorActions = () => useContext(EditorActionsContext);
