/**
 * Curated rendering and interaction selectors for the editor canvas.
 * Components consume these view-facing operations without depending on the
 * editor-core package directly.
 */
export {
  clampCanvasPan,
  clipSymmetryLine,
  convertPixelsToSrgb,
  workingColorProfile,
  createAsepriteSelectionAntsState,
  documentToScreen,
  executeEditorCommand,
  getAutoCelGuides,
  getXpriteToolCapabilities,
  hitSelectionHandles,
  inlineTextCaretAt,
  INLINE_TEXT_MOVE_REGION_PADDING,
  isBackgroundLayer,
  isSelectionTool,
  isShapeTool,
  isTwoPointShape,
  maskContains,
  documentAutoGuideGeometry,
  documentGuideDashVisible,
  libreSpriteGridGeometry,
  documentLayerEdgeGeometry,
  libreSpritePixelGridGeometry,
  asepriteSelectionBoundaryWhite,
  asepriteSelectionHandleRect,
  timelineWheelFrameIndex,
  libreSpriteWorkingBrushColor,
  offsetGridLines,
  paintAsepriteSelectionAnts,
  projectSelectionBoundarySegments,
  requestAsepriteSelectionAntsTick,
  resolveSymmetryMode,
  screenToDocument,
  selectionBoundaryContains,
  selectionBoundarySegments,
  selectionHandlePositions,
  selectionPivotPoint,
  selectionTransformPivotPoint,
  selectionShaderOffset,
  sliceKeyAt,
  stepZoom,
  stepAsepriteZoom,
  symmetryAxisPosition,
  symmetryHandles,
  tiledCanvasLayout,
  tileNumberLabels,
  syncAsepriteSelectionAnts,
  AsepriteInk,
  SelectionMode,
  canMoveSelectionPixels,
  canTransformTimelineSelection,
  selectionModeForInput,
  UINT8_MAX,
  editorFrameGeometry,
  editorScrollDragPan,
  chooseShortcutTool,
  keepDocumentOrigin,
  resolveShortcut,
} from "@xprite/editor-core";

export type {
  EditorScrollAxis,
  EditorTool as CoreTool,
  InlineTextDraft,
  AsepriteSelectionAntsState,
  SelectionBoundarySegment,
  PixelMask,
  Point,
  PointerInput,
  Rect,
  SelectionHandle,
  SymmetryHandle,
  ViewSettings,
} from "@xprite/editor-core";
