import { desktopPatternTokens } from "$/base/theme/desktop-pattern-tokens";
import { noteTokens } from "$/base/theme/note-tokens";
import {
  semanticFontFamilies,
  semanticPresentationTokens,
} from "$/base/theme/semantic-presentation-tokens";
import type { UiThemeArtwork, UiThemeTokens } from "$/base/theme/theme-definition";

/** Shared semantic CSS roles for DOM controls, including controls mounted in portals. */
export function themeTokens(
  { definition: { colors, typography, controlParts }, tokens }: UiThemeArtwork,
  inherited: UiThemeTokens = {},
): UiThemeTokens {
  const fonts = semanticFontFamilies(typography);
  return {
    // A nested skin must not inherit optional tokens owned only by its parent's skin.
    ...Object.fromEntries(Object.keys(inherited).map((name) => [name, "initial"])),
    ...semanticPresentationTokens({
      primaryFont: fonts.primary,
      compactFont: fonts.compact,
      ink: colors.text,
      mutedInk: colors.disabled,
      paper: colors.window_face,
      line: colors.disabled,
      desktop: colors.workspace,
      chrome: colors.face,
      border: colors.popup_window_border,
      canvas: colors.editor_face,
      link: colors.link_text,
    }),
    ...noteTokens(fonts.compact),
    ...desktopPatternTokens(),
    "--ui-menu-navigation-height": "20px",
    "--ui-menu-navigation-font-size": "var(--ui-text-default-size)",
    "--ui-menu-navigation-face": colors.window_face,
    "--ui-menu-navigation-ink": colors.text,
    "--ui-menu-navigation-highlight-face": colors.selected,
    "--ui-menu-navigation-highlight-ink": colors.selected_text,
    "--ui-window-title-background": "transparent",
    "--xse-font": fonts.primary,
    "--ui-window-title-inset": "10px",
    "--ui-window-title-reserved-width": "36px",
    "--ui-window-title-offset": "0px",
    "--ui-window-title-transform": "none",
    "--ui-window-title-padding": "0px",
    "--ui-window-title-top": "10px",
    "--ui-window-title-height": "16px",
    "--ui-window-title-max-width": "none",
    "--ui-window-title-overflow": "visible",
    "--ui-tab-label-top": "8px",
    "--ui-tab-icon-top": "6px",
    "--ui-tab-close-icon-top": "8px",
    "--ui-tab-focus-outline": "none",
    "--ui-combobox-disabled-opacity": "1",
    "--ui-combobox-popup-shadow": "none",
    "--ui-button-disabled-opacity": "1",
    "--xse-text": colors.text,
    "--xse-window": colors.window_face,
    "--xse-border": colors.popup_window_border,
    "--xse-workspace": colors.workspace,
    "--xse-disabled": colors.disabled,
    "--ui-panel-highlight": colors.hot_face,
    "--ui-surface-neutral-face": colors.window_face,
    "--ui-surface-neutral-ink": colors.text,
    "--ui-surface-accent-face": colors.window_face,
    "--ui-surface-accent-ink": colors.text,
    "--ui-surface-informative-face": colors.window_face,
    "--ui-surface-informative-ink": colors.text,
    "--ui-surface-positive-face": colors.window_face,
    "--ui-surface-positive-ink": colors.text,
    "--ui-surface-warning-face": colors.window_face,
    "--ui-surface-warning-ink": colors.text,
    "--ui-navigation-list-font-family": "var(--xse-font)",
    "--ui-navigation-list-face": colors.listitem_normal_face,
    "--ui-navigation-list-ink": colors.listitem_normal_text,
    "--ui-navigation-list-selected-face": colors.listitem_selected_face,
    "--ui-navigation-list-selected-ink": colors.listitem_selected_text,
    "--ui-navigation-list-row-height": `${controlParts?.listBox?.rowHeight ?? 24}px`,
    "--ui-navigation-list-font-size": "16px",
    "--ui-button-quiet-ink": colors.menuitem_normal_text,
    "--ui-button-quiet-active-ink": colors.menuitem_hot_text,
    "--ui-button-quiet-active-face": colors.menuitem_hot_face,
    "--ui-field-face": colors.textbox_face,
    "--ui-field-text": colors.textbox_text,
    "--ui-panel-header-face": colors.window_face,
    "--ui-heading-face": colors.workspace,
    "--ui-heading-ink": colors.background,
    "--ui-curve-background": colors.textbox_face,
    "--ui-curve-border": colors.popup_window_border,
    "--ui-curve-grid": colors.disabled,
    "--ui-curve-line": colors.text,
    "--ui-curve-point": colors.text,
    "--ui-native-slider-track-face": colors.textbox_face,
    "--ui-native-slider-fill": colors.selected,
    "--ui-native-slider-thumb-face": colors.face,
    "--ui-native-slider-border": colors.popup_window_border,
    "--ui-native-slider-radius": "0",
    "--ui-native-slider-thumb-shadow": "none",
    "--ui-scrollbar-track-pattern": "none",
    "--ui-scrollbar-thumb-grip": "none",
    "--ui-focus-ring-color": colors.popup_window_border,
    "--ui-overlay-face": colors.window_face,
    "--ui-overlay-text": colors.text,
    "--ui-overlay-edge": colors.popup_window_border,
    "--ui-overlay-shadow": colors.editor_view_face,
    "--ui-context-menu-edge": colors.popup_window_border,
    "--ui-button-surface-ink": colors.button_normal_text,
    "--ui-button-surface-face": colors.window_face,
    "--ui-button-surface-line": colors.disabled,
    "--ui-button-surface-selected-ink": colors.menuitem_hot_text,
    "--ui-button-surface-selected-face": colors.menuitem_hot_face,
    "--ui-button-surface-hot-ink": "var(--ui-button-surface-selected-ink)",
    "--ui-button-surface-hot-face": "var(--ui-button-surface-selected-face)",
    "--ui-button-surface-pressed-ink": "var(--ui-button-surface-selected-ink)",
    "--ui-button-surface-pressed-face": "var(--ui-button-surface-selected-face)",
    "--ui-button-surface-border-width": "1px",
    "--ui-button-surface-radius": "0",
    "--ui-button-surface-shadow": "none",
    "--ui-button-surface-active-shadow": "none",
    ...tokens,
  };
}
