/** Search only the settings available in this editor; unsupported sections stay disabled. */
export const PREFERENCES_SEARCH_LABELS: Readonly<Record<string, readonly string[]>> = {
  General: [
    "Appearance mode:",
    "Light",
    "Dark",
    "System",
    "UI Element Scaling:",
    "Language:",
    "Show editor menu bar",
    "Show shortcut toolbar",
    "Show tool options in toolbar",
    "Show Home tab when editor starts",
    "Expand menu bar items on mouseover",
  ],
  Files: [
    "Default extension for:",
    "File > Save:",
    "File > Export (one image):",
    "File > Export (animation):",
    "Recent Items:",
    "Clear",
    "Recover Files",
    "Automatically save recovery data every",
    "Keep edited sprite data for",
  ],
  Editor: [
    "Zoom with scroll wheel",
    "Zoom sliding two fingers up or down",
    "Zoom from center with scroll wheel",
    "Zoom from center with keys",
    "Auto-scroll on editor edges",
    "Auto-fit on screen when a sprite is opened",
    "Preview straight line immediately with the Pencil tool",
    "Discard custom brush whenever the eyedropper is used",
    "Show scroll-bars in sprite editor",
    "Wheel device:",
    "Mouse wheel",
    "Trackpad",
  ],
  Selection: [
    "Editor Selection",
    "Transform cels in selected layers or frames on timeline",
    "Allow moving selection edges",
    "Disable transformation handles when key modifiers are pressed",
    "Move selection on Add mode",
    "Adjust opaque/transparent mode automatically",
    'Keep selection after "Edit > Delete" command',
    "Show selection edges automatically when the selection is modified",
    "Select a grid tile with double-click",
  ],
  Timeline: [
    "Show timeline automatically",
    "Rewind on Stop",
    "Default First Frame:",
    "Timeline Range Selection",
    "Keep selection",
    "Select on Click",
    "Select on Shift + Click",
    "Select on Drag",
    "Drag & drop from edges",
    "Reset",
  ],
  Cursors: [
    "UI Mouse Cursor",
    "Use native mouse cursors",
    "Mouse Cursor Scale:",
    "Painting Cursors",
    "Crosshair Type:",
    "Brush Preview:",
    "Tile Preview:",
    "Crosshair & Brush Edges Color:",
    "Snap To Grid when the option is enabled",
  ],
  Background: [
    "Checkered Background",
    "Checker size:",
    "Size:",
    "Width:",
    "Height:",
    "Colors:",
    "Background color 1",
    "Background color 2",
    "Apply Zoom",
    "Zoom checkerboard with sprite",
    "Reset",
  ],
  Grid: [
    "Grid X",
    "Grid Y",
    "Grid Width",
    "Grid Height",
    "Grid color:",
    "Grid opacity:",
    "Automatic opacity",
    "Pixel Grid",
    "Pixel grid color:",
    "Pixel grid opacity:",
    "Reset",
  ],
  "Guides & Slices": [
    "Guides",
    "Layer Edges Color:",
    "Auto Guides Color:",
    "Slices",
    "Default Color:",
    "Prefer slice keyframes (obsolete behavior)",
  ],
  Undo: [
    "Undo Limit:",
    "Go to modified frame/layer",
    "Allow non-linear history",
    "Show Undo Tooltip",
  ],
  Experimental: [
    "User Interface",
    "Compose groups separately",
    "Tooltip Delay:",
    "Opacity for non-active layers:",
  ],
  Tablet: [
    "ui.touch.pinch.zoom",
    "ui.touch.pinch.zoom.smooth",
    "ui.touch.pinch.zoom.snap.on.release",
    "ui.touch.pinch.zoom.stepped",
    "Single-finger action",
    "Automatic: draw with fingers until a pen is used",
    "Draw with fingers",
    "Navigate with fingers",
    "Two-finger tap to undo",
    "Three-finger tap to redo",
    "Hold to repeat undo and redo",
    "Touch and hold to pick a color",
    "Repeat delay (ms)",
    "Color-pick delay (ms)",
  ],
  Diagnostics: [
    "ui.diagnostics.entry.count",
    "ui.diagnostics.latest",
    "ui.diagnostics.export.button",
    "ui.diagnostics.view.button",
    "ui.diagnostics.clear.button",
    "ui.diagnostics.technical-support",
  ],
  Reset: [
    "ui.reset.preferences.title",
    "ui.reset.preferences.configuration",
    "ui.reset.preferences.tools",
    "ui.reset.preferences.filters",
    "ui.reset.preferences.shades",
    "ui.reset.preferences.recent",
    "ui.reset.preferences.per-file",
    "ui.reset.preferences.brushes",
    "ui.reset.preferences.toggle",
  ],
};
